/* Baits*/
INSERT IGNORE INTO `items` (`item`, `label`, `weight`, `remove`, `type`, `action`) VALUES 
                           ('p_baitBread01x', 'Bread Bait', '0.1', '0', 'item', 'usable'),
                           ('p_baitCorn01x', 'Corn Bait', '0.1', '0', 'item', 'usable'),
                           ('p_baitCheese01x', 'Cheese Bait', '0.1', '0', 'item', 'usable'),
                           ('p_baitWorm01x', 'Worm Bait', '0.1', '0', 'item', 'usable'),
                           ('p_baitCricket01x', 'Cricket Bait', '0.1', '0', 'item', 'usable'),
                           ('p_crawdad01x', 'Crawfish Bait', '0.1', '0', 'item', 'usable'),
                           ('p_finishedragonfly01x', 'Dragonfly Lure', '0.1', '0', 'item', 'usable'),
                           ('p_FinisdFishlure01x', 'Fish Lure', '0.1', '0', 'item', 'usable'),
                           ('p_finishdcrawd01x', 'Crawfish Lure', '0.1', '0', 'item', 'usable'),
                           ('p_finishedragonflylegendary01x', 'Legendary Dragonfly Lure', '0.1', '0', 'item', 'usable'),
                           ('p_finisdfishlurelegendary01x', 'Legendary Fish Lure', '0.1', '0', 'item', 'usable'),
                           ('p_finishdcrawdlegendary01x', 'Legendary Crawfish Lure', '0.1', '0', 'item', 'usable'),
                           ('p_lgoc_spinner_v4', 'Spinner V4', '0.1', '0', 'item', 'usable'),
                           ('p_lgoc_spinner_v6', 'Spinner V6', '0.1', '0', 'item', 'usable');

/* Fish Types*/
INSERT IGNORE INTO `items` (`item`, `label`, `weight`, `remove`, `type`, `action`) VALUES 
                           ('a_c_fishbluegil_01_ms', 'Blue Gil (Medium)', '0.4', '0', 'item', 'none'),
                           ('a_c_fishbluegil_01_sm', 'Blue Gil (Small)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishbullheadcat_01_ms', 'Bullhead Cat (Medium)', '0.4', '0', 'item', 'none'),
                           ('a_c_fishbullheadcat_01_sm', 'Bullhead Cat (Small)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishchainpickerel_01_ms', 'Chain Pickerel (Medium)', '0.4', '0', 'item', 'none'),
                           ('a_c_fishchainpickerel_01_sm', 'Chain Pickerel (Small)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishchannelcatfish_01_lg', 'Channel Catfish (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishchannelcatfish_01_xl', 'Channel Catfish (Extra Large)', '0.8', '0', 'item', 'none'),
                           ('a_c_fishlakesturgeon_01_lg', 'Lake Sturgeon (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishlargemouthbass_01_lg', 'Large Mouth Bass (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishlargemouthbass_01_ms', 'Large Mouth Bass (Medium)', '0.4', '0', 'item', 'none'),
                           ('a_c_fishlongnosegar_01_lg', 'Long Nose Gar (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishmuskie_01_lg', 'Muskie (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishnorthernpike_01_lg', 'Northern Pike (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishperch_01_ms', 'Perch (Medium)', '0.4', '0', 'item', 'none'),
                           ('a_c_fishperch_01_sm', 'Perch (Small)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishrainbowtrout_01_lg', 'Rainbow Trout (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishrainbowtrout_01_ms', 'Rainbow Trout (Medium)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishredfinpickerel_01_ms', 'Red Fin Pickerel (Medium)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishredfinpickerel_01_sm', 'Red Fin Pickerel (Small)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishrockbass_01_ms', 'Rock Bass (Medium)', '0.4', '0', 'item', 'none'),
                           ('a_c_fishrockbass_01_sm', 'Rock Bass (Small)', '0.3', '0', 'item', 'none'),
                           ('a_c_fishsalmonsockeye_01_lg', 'Salmon Sockeye (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishsalmonsockeye_01_ml', 'Salmon Sockeye (Medium-Large)', '0.5', '0', 'item', 'none'),
                           ('a_c_fishsalmonsockeye_01_ms', 'Salmon Sockeye (Medium)', '0.4', '0', 'item', 'none'),
                           ('a_c_fishsmallmouthbass_01_lg', 'Small Mouth Bass (Large)', '0.6', '0', 'item', 'none'),
                           ('a_c_fishsmallmouthbass_01_ms', 'Small Mouth Bass (Medium)', '0.3', '0', 'item', 'none');